---
title: "Jeopardy steaks"
author: "Alan Jern"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(lubridate)
library(here)
```

```{r}
j_data <- read_csv(here("jeopardy_winners.csv"))
```

```{r consecutive-wins}
streak_data <- j_data |> 
  # filter out special games:
  # - tournaments
  # - championship games
  # - "battle of the decades"
  # - celebrity jeopardy
  # - kids week / back to school week
  filter(is.na(str_match(str_to_lower(comments), "tournament"))) |>
  filter(is.na(str_match(str_to_lower(comments), "championship"))) |>
  filter(is.na(str_match(str_to_lower(comments), "battle"))) |>
  filter(is.na(str_match(str_to_lower(comments), "celebrity"))) |>
  filter(is.na(str_match(str_to_lower(comments), "kids"))) |>
  filter(is.na(str_match(str_to_lower(comments), "week"))) |>
  # only look at winners
  filter(winner == TRUE) |> 
  arrange(show_number) |> 
  mutate(total_wins = sequence(rle(contestant)$lengths)) |> 
  # only keep shows after the win limit was lifted
  filter(air_date >= "2003-09-08")
```


```{r convert-show-number-function}
convert_to_air_date <- function(show_n) {
  return(streak_data |> filter(show_number %in% show_n) |> pull(air_date))
}
```



```{r plot-steaks, fig.dim=c(9,4)}
library(gghighlight)
library(showtext)
library(ggthemes)

font_add_google("Inter", "inter")
font_add_google("Barlow", "barlow")
font_add_google("Roboto Slab", "rs")
showtext_auto()

p1 <- ggplot() +
  geom_point(data = streak_data,
             aes(x = air_date, y = total_wins),
             #color = "#081484",
             color = "white",
             size = 0.2) +
  # highlight the top 5 longest streaks
  geom_point(data = streak_data |> 
               filter(contestant == "Ken Jennings" |
                        contestant == "Amy Schneider" |
                        contestant == "Matt Amodio" |
                        contestant == "James Holzhauer" |
                        contestant == "Mattea Roach"),
             aes(x = air_date, y = total_wins),
             #color = "#081484",
             color = "#FFCC00",
             size = 0.2) +
  annotate("text", x = as_datetime("2005-03-01"), y = 65,
           label = "Ken Jennings",
           hjust = 0,
           size = 3,
           color = "white",
           family = "barlow") +
  annotate("text", x = as_datetime("2019-03-01"), y = 26,
           label = "James Holzhauer",
           hjust = 1,
           size = 3,
           color = "white",
           family = "barlow") +
  annotate("segment",
           x = as_datetime("2021-07-01"),
           xend = as_datetime("2020-02-01"),
           y = 29, yend = 43,
           color = "gray80") +
  annotate("text", x = as_datetime("2018-09-01"), y = 46,
           label = "Matt Amodio",
           hjust = 0,
           size = 3,
           color = "white",
           family = "barlow") +
  annotate("segment",
           x = as_datetime("2021-10-01"),
           xend = as_datetime("2020-07-01"),
           y = 38, yend = 53,
           color = "gray80") +
  annotate("text", x = as_datetime("2019-06-01"), y = 56,
           label = "Amy Schneider",
           hjust = 0,
           size = 3,
           color = "white",
           family = "barlow") +
  annotate("segment",
           x = as_datetime("2022-06-01"),
           xend = as_datetime("2022-08-01"),
           y = 25, yend = 45,
           color = "gray80") +
  annotate("text", x = as_datetime("2021-06-01"), y = 48,
           label = "Mattea Roach",
           hjust = 0,
           size = 3,
           color = "white",
           family = "barlow") +
  theme_hc(style = "darkunica") +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.title = element_text(family = "rs"),
        plot.subtitle = element_text(family = "barlow"),
        legend.text = element_text(family = "barlow"),
        legend.title = element_text(family = "barlow"),
        axis.title = element_text(family = "barlow"),
        axis.text = element_text(family = "barlow")) +
  labs(
    title = "Jeopardy! win streaks after the win limit was eliminated",
    subtitle = "Each dot is one win • Stacked dots are streaks",
    x = NULL,
    y = "Wins",
    caption = "Data: J! Archive"
  )
plot(p1)

ggsave('win_streaks.png', width = 9, height = 4)
```
```{r streaks-by-season}
streaks_by_season <- j_data |> 
  # filter out special games:
  # - tournaments
  # - championship games
  # - celebrity jeopardy
  # - kids week / back to school week
  filter(is.na(str_match(str_to_lower(comments), "tournament"))) |>
  filter(is.na(str_match(str_to_lower(comments), "championship"))) |>
  filter(is.na(str_match(str_to_lower(comments), "battle"))) |>
  filter(is.na(str_match(str_to_lower(comments), "celebrity"))) |>
  filter(is.na(str_match(str_to_lower(comments), "kids"))) |>
  filter(is.na(str_match(str_to_lower(comments), "week"))) |>
  # only look at winners
  filter(winner == TRUE) |> 
  arrange(show_number) |> 
  mutate(total_wins = sequence(rle(contestant)$lengths)) |> 
  group_by(contestant, season) |> 
  summarize(streak_length = max(total_wins)) |> 
  ungroup()
```

```{r plot-streak-length-by-season}
library(ggdist)

p2 <- ggplot() +
  # win limit lifted at beginning of season 20
  geom_rect(aes(xmin = 0, xmax = 19.5, ymin = -Inf, ymax = Inf),
            fill = "#00008b", alpha = 0.1) +
  scale_x_continuous(breaks = c(1,10,20,30,38)) +
  stat_interval(data = streaks_by_season,
                aes(x = season, y = streak_length)) +
  annotate("text", x = 17, y = 15,
           label = "Before Season 20, streaks\nwere limited to 5",
           hjust = 1,
           size = 3,
           family = "barlow") +
  geom_curve(aes(x = 33, xend = 37, y = 25, yend = 28),
             curvature = -0.2, 
             arrow = arrow(length = unit(0.2,"cm"),
                           type = "closed"),
             color = "gray50") +
  annotate("text", x = 29, y = 23,
           label = "Season 38 is an outlier",
           hjust = 0,
           size = 3,
           family = "barlow") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white"),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        plot.title = element_text(family = "rs"),
        plot.subtitle = element_text(family = "barlow"),
        legend.text = element_text(family = "barlow"),
        legend.title = element_text(family = "barlow"),
        axis.title = element_text(family = "barlow"),
        axis.text = element_text(family = "barlow")) +
  scale_color_brewer(palette = "Reds") +
  labs(title = "Jeopardy! win streak lengths over time",
       subtitle = "Distribution of streak lengths by season",
       x = "Season",
       y = NULL,
       color = "Proportion of streaks this length or less",
       caption = "Data: J! Archive")
plot(p2)

ggsave('win_streak_lengths.png')
```
```{r long-streak-pct-by-season}
long_streaks_by_season <- streaks_by_season |> 
  mutate(long_streak = streak_length >= 5) |> 
  group_by(season, long_streak) |> 
  summarize(n = n()) |> 
  mutate(prop = n/sum(n))
```

```{r}
p3 <- ggplot() +
  # win limit lifted at beginning of season 20
  geom_rect(aes(xmin = 0, xmax = 19.5, ymin = -Inf, ymax = Inf),
            fill = "#00008b", alpha = 0.1) +
  scale_x_continuous(breaks = c(1,10,20,30,38)) +
  geom_col(data = long_streaks_by_season |> filter(long_streak == TRUE),
           aes(x = season, y = n),
           fill = "lightsteelblue4") +
  annotate("text", x = 3, y = 7.5,
           label = "Before Season 20, streaks\nwere limited to 5",
           hjust = 0,
           size = 3,
           family = "barlow") +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white"),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        plot.title = element_text(family = "rs"),
        plot.subtitle = element_text(family = "barlow"),
        legend.text = element_text(family = "barlow"),
        legend.title = element_text(family = "barlow"),
        axis.title = element_text(family = "barlow"),
        axis.text = element_text(family = "barlow")) +
  scale_color_brewer(palette = "Reds") +
  labs(title = "Number of win streaks of at least 5 games each season",
       x = "Season",
       y = NULL,
       caption = "Data: J! Archive")
plot(p3)

ggsave("number_of_streaks.png")
```

